<?php

namespace Database\Seeders;

use App\Models\Produk;
use App\Models\SkinType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    public function run()
    {
        $produk = [
            [
                'nama' => 'Avoskin YSB Serum Infused Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Cleanser dengan kandungan serum untuk kulit berminyak.',
                'harga' => 45000,
                'rating' => 4.5,
                'popularitas' => 80,
                'niacinamide' => 1, 'retinol' => 1, 'salicylic_acid' => 1, 'glycolic_acid' => 1,
                'hyaluronic_acid' => 1, 'dimethicone' => 0, 'glycerin' => 0, 'vitamin_e' => 0,
                'minyak_jojoba' => 0, 'urea' => 0, 'aloe_vera' => 0, 'ceramide' => 0,
                'shea_butter' => 0, 'panthenol' => 0, 'formula_oil_free' => 0, 'zinc' => 0,
                'squalane' => 0, 'zinc_oxide' => 0, 'oil_free' => 0, 'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'La Roche-Posay Effaclar Purifying Foaming Gel',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Gel pembersih wajah yang membersihkan dan menenangkan.',
                'harga' => 155000,
                'rating' => 4.8,
                'popularitas' => 90,
                'niacinamide' => 0, 'retinol' => 0, 'salicylic_acid' => 1, 'glycolic_acid' => 1,
                'hyaluronic_acid' => 0, 'dimethicone' => 0, 'glycerin' => 0, 'vitamin_e' => 0,
                'minyak_jojoba' => 0, 'urea' => 0, 'aloe_vera' => 0, 'ceramide' => 0,
                'shea_butter' => 0, 'panthenol' => 0, 'formula_oil_free' => 0, 'zinc' => 0,
                'squalane' => 0, 'zinc_oxide' => 0, 'oil_free' => 0, 'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'Emina Bright Stuff for Acne Prone Skin Face Wash',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Face wash ringan untuk kulit berjerawat.',
                'harga' => 28000,
                'rating' => 4.3,
                'popularitas' => 70,
                'niacinamide' => 1, 'retinol' => 0, 'salicylic_acid' => 1, 'glycolic_acid' => 0,
                'hyaluronic_acid' => 0, 'dimethicone' => 0, 'glycerin' => 0, 'vitamin_e' => 0,
                'minyak_jojoba' => 0, 'urea' => 0, 'aloe_vera' => 0, 'ceramide' => 0,
                'shea_butter' => 0, 'panthenol' => 0, 'formula_oil_free' => 0, 'zinc' => 0,
                'squalane' => 0, 'zinc_oxide' => 0, 'oil_free' => 0, 'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'La Roche-Posay Toleriane Hydrating Gentle Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Cleanser yang lembut dan melembapkan untuk kulit kering.',
                'harga' => 180000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'BeautyStat Microbiome Barrier Repair Purifying Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Cleanser yang dirancang untuk memperbaiki dan melindungi mikrobioma kulit kering.',
                'harga' => 220000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 75, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'Wardah Lightening Micellar Gentle Wash',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Micellar facial wash yang lembut untuk kulit kering dan sensitif.',
                'harga' => 49000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.4,   // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 80, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'Cetaphil Gentle Skin Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Cleanser lembut untuk semua jenis kulit termasuk sensitif.',
                'harga' => 95000,
                'rating' => 4.7,
                'popularitas' => 88,
                'niacinamide' => 1, 'retinol' => 0, 'salicylic_acid' => 0, 'glycolic_acid' => 0,
                'hyaluronic_acid' => 0, 'dimethicone' => 0, 'glycerin' => 1, 'vitamin_e' => 0,
                'minyak_jojoba' => 0, 'urea' => 0, 'aloe_vera' => 0, 'ceramide' => 0,
                'shea_butter' => 0, 'panthenol' => 0, 'formula_oil_free' => 0, 'zinc' => 0,
                'squalane' => 0, 'zinc_oxide' => 0, 'oil_free' => 0, 'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'CeraVe Hydrating Facial Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Facial cleanser lembut untuk kulit normal, menghidrasi dan membersihkan.',
                'harga' => 125000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,   // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'Avoskin Natural Sublime Facial Cleanser',
                'jenis_produk' => 'facial_wash',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Facial cleanser alami untuk kulit normal, membersihkan dan melembapkan.',
                'harga' => 135000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 78, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 1,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 1,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'Azarine Oil-Free Brightening Daily Moisturizer',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Moisturizer ringan bebas minyak untuk kulit cerah.',
                'harga' => 60000,
                'rating' => 4.4,
                'popularitas' => 72,
                'niacinamide' => 1, 'retinol' => 0, 'salicylic_acid' => 0, 'glycolic_acid' => 0,
                'hyaluronic_acid' => 1, 'dimethicone' => 0, 'glycerin' => 0, 'vitamin_e' => 0,
                'minyak_jojoba' => 0, 'urea' => 0, 'aloe_vera' => 0, 'ceramide' => 0,
                'shea_butter' => 0, 'panthenol' => 0, 'formula_oil_free' => 1, 'zinc' => 0,
                'squalane' => 0, 'zinc_oxide' => 0, 'oil_free' => 0, 'titanium_dioxide' => 0,
            ],
            [
                'nama' => 'COSRX Oil-Free Ultra Moisturizing Lotion',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Lotion pelembap bebas minyak untuk kulit berminyak, melembapkan tanpa menyumbat pori.',
                'harga' => 200000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 1,
                'titanium_dioxide' => 0,
            ],
            [
                // Cetaphil Pro Oil Absorbing Moisturizer SPF 30
                'nama' => 'Cetaphil Pro Oil Absorbing Moisturizer SPF 30',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Moisturizer bebas minyak dengan SPF 30 untuk kulit berminyak, membantu menyerap minyak berlebih.',
                'harga' => 350000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 80, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 1,
                'titanium_dioxide' => 0,
            ],

            [
                // CeraVe Intensive Moisturizing Lotion
                'nama' => 'CeraVe Intensive Moisturizing Lotion',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Lotion pelembap intensif untuk kulit kering, dengan kandungan ceramide dan asam hialuronat.',
                'harga' => 225000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.8,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 1,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 1,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Typology Nourishing Moisturizer
                'nama' => 'Typology Nourishing Moisturizer',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Moisturizer nourishing untuk kulit kering dengan bahan alami untuk melembapkan.',
                'harga' => 400000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.5,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 75, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 1,
                'urea' => 0,
                'aloe_vera' => 1,
                'ceramide' => 0,
                'shea_butter' => 1,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                // Cetaphil Pro Oil Absorbing Moisturizer SPF 30
                'nama' => 'Cetaphil Pro Oil Absorbing Moisturizer SPF 30',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Moisturizer bebas minyak dengan SPF 30 untuk kulit berminyak, membantu menyerap minyak berlebih.',
                'harga' => 350000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 80, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 1,
                'titanium_dioxide' => 0,
            ],
            [
                // CeraVe Intensive Moisturizing Lotion
                'nama' => 'CeraVe Intensive Moisturizing Lotion',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Lotion pelembap intensif untuk kulit kering, dengan kandungan ceramide dan asam hialuronat.',
                'harga' => 225000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.8,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 1,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 1,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                // Typology Nourishing Moisturizer
                'nama' => 'Typology Nourishing Moisturizer',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Moisturizer nourishing untuk kulit kering dengan bahan alami untuk melembapkan.',
                'harga' => 400000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.5,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 75, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 1,
                'urea' => 0,
                'aloe_vera' => 1,
                'ceramide' => 0,
                'shea_butter' => 1,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
            [
                // The Ordinary Natural Moisturizing Factors + HA
                'nama' => 'The Ordinary Natural Moisturizing Factors + HA',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Moisturizer dengan kandungan hyaluronic acid yang membantu menjaga kelembapan kulit.',
                'harga' => 180000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 1,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 1,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // CeraVe Daily Moisturizing Cream
                'nama' => 'CeraVe Daily Moisturizing Cream',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Pelembap harian untuk kulit normal, mengandung ceramide dan asam hialuronat.',
                'harga' => 260000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.8,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 90, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 1,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Kahf Moisturizer
                'nama' => 'Kahf Moisturizer',
                'jenis_produk' => 'moisturizer',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Moisturizer untuk kulit normal dengan formula ringan yang melembapkan.',
                'harga' => 100000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.4,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 78, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 1,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 1,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Erha Acne Care Lab Sun Friendly SPF 30
                'nama' => 'Erha Acne Care Lab Sun Friendly SPF 30',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Tabir surya SPF 30 untuk kulit berminyak dan berjerawat, melindungi kulit dari sinar UV.',
                'harga' => 185000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 88, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 1,
                'titanium_dioxide' => 1,
            ],

            [
                // Wardah UV Shield Aqua Fresh Essence SPF 50
                'nama' => 'Wardah UV Shield Aqua Fresh Essence SPF 50',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Tabir surya dengan SPF 50 untuk melindungi kulit dari sinar UV.',
                'harga' => 95000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.5,   // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 80, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 1,
                'titanium_dioxide' => 1,
            ],

            [
                // Somethinc Holyshield UV Watery Sunscreen Gel SPF 50+
                'nama' => 'Somethinc Holyshield UV Watery Sunscreen Gel SPF 50+',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'berminyak',
                'deskripsi' => 'Tabir surya SPF 50+ dengan tekstur gel yang ringan dan tidak lengket.',
                'harga' => 200000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 90, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 1,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 1,
                'titanium_dioxide' => 1,
            ],
            [
                // CeraVe 100% Mineral Sunscreen SPF 50
                'nama' => 'CeraVe 100% Mineral Sunscreen SPF 50',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Tabir surya mineral SPF 50 untuk kulit kering, melindungi dari sinar UV dengan kandungan ceramide.',
                'harga' => 280000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 85, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 1,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 1,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 1,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Joylab Skintone Moisture Tint SPF 30
                'nama' => 'Joylab Skintone Moisture Tint SPF 30',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Tinted sunscreen dengan SPF 30, melembapkan kulit kering sambil memberikan sedikit coverage.',
                'harga' => 180000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.5,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 80, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Neutrogena Sheer Zinc Dry-Touch SPF 50
                'nama' => 'Neutrogena Sheer Zinc Dry-Touch SPF 50',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'kering',
                'deskripsi' => 'Tabir surya SPF 50 yang memberikan perlindungan maksimal dengan teknologi dry-touch, cocok untuk kulit kering.',
                'harga' => 200000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.6,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 82, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 0,
                'dimethicone' => 0,
                'glycerin' => 0,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 1,
                'squalane' => 0,
                'zinc_oxide' => 1,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Skin Aqua UV Moisture Milk SPF 50
                'nama' => 'Skin Aqua UV Moisture Milk SPF 50',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Tabir surya SPF 50 dengan tekstur milk yang melembapkan kulit normal.',
                'harga' => 120000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.7,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 90, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 1,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],

            [
                // Biore UV Aqua Rich Watery Essence SPF 50
                'nama' => 'Biore UV Aqua Rich Watery Essence SPF 50',
                'jenis_produk' => 'sunscreen',
                'skin_type_name' => 'normal',
                'deskripsi' => 'Tabir surya dengan tekstur essence yang ringan dan cepat meresap, memberikan perlindungan SPF 50.',
                'harga' => 140000,  // Anda bisa menyesuaikan harga sesuai kebutuhan
                'rating' => 4.8,    // Anda bisa menyesuaikan rating sesuai kebutuhan
                'popularitas' => 95, // Anda bisa menyesuaikan popularitas sesuai kebutuhan
                'niacinamide' => 0,
                'retinol' => 0,
                'salicylic_acid' => 0,
                'glycolic_acid' => 0,
                'hyaluronic_acid' => 1,
                'dimethicone' => 0,
                'glycerin' => 1,
                'vitamin_e' => 0,
                'minyak_jojoba' => 0,
                'urea' => 0,
                'aloe_vera' => 0,
                'ceramide' => 0,
                'shea_butter' => 0,
                'panthenol' => 0,
                'formula_oil_free' => 0,
                'zinc' => 0,
                'squalane' => 0,
                'zinc_oxide' => 0,
                'oil_free' => 0,
                'titanium_dioxide' => 0,
            ],
        ];

        foreach ($produk as &$item) {
            $item['created_at'] = now();
            $item['updated_at'] = now();
        }

        foreach ($produk as $data) {
            $skinType = SkinType::where('name', $data['skin_type_name'])->first();
            if ($skinType) {
                $data['skin_type_id'] = $skinType->id;
                unset($data['skin_type_name']);
                Produk::create($data);
            }
        }
    }
}
